# Generated by Django 5.2.8 on 2025-12-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('modules_count', models.IntegerField(default=1)),
                ('teacher', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/')),
                ('rating', models.FloatField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('video_duration', models.TimeField()),
                ('description', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0)),
                ('homework', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_exam', models.IntegerField(default=0)),
                ('failed_exam', models.IntegerField(default=0)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='erp.course')),
                ('subjects', models.ManyToManyField(related_name='module_subjects', to='erp.subject')),
            ],
        ),
    ]
