# Generated by Django 5.2.8 on 2025-12-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='studiying_now',
            field=models.IntegerField(default=0),
        ),
    ]
