# Generated by Django 5.2.8 on 2025-11-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_last_name_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=False, max_length=40),
        ),
    ]
