# Generated by Django 5.2.8 on 2025-11-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email',
        ),
    ]
