# Generated by Django 5.2.8 on 2025-11-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_teacher_email_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=False, max_length=30, unique=True),
        ),
    ]
