# Generated by Django 5.2.8 on 2025-11-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=False, max_length=30, unique=True),
        ),
    ]
