# Generated by Django 5.2.8 on 2025-12-01 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_course_studiying_now'),
        ('user', '0007_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_course', to='erp.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
