# Generated by Django 5.2.8 on 2025-12-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_student_course_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='Student', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='Teacher', max_length=10),
        ),
    ]
